basePath: /
definitions:
  dto.OauthRequestBody:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  dto.OauthResponse:
    properties:
      accessToken:
        type: string
      expiredAt:
        type: string
      sync:
        type: boolean
    type: object
  dto.UpdateUserRequestBody:
    properties:
      name:
        type: string
    type: object
  dto.UpdateUserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: hch950627@naver.com
    name: API Support
  description: API Server for Banana Account Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Banana Account Book API
  version: "1.0"
paths:
  /auth/{provider}:
    get:
      consumes:
      - application/json
      description: 각 provider에 의한 Oauth 링크 반환
      parameters:
      - description: Authentication provider
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved auth URL
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      summary: Get oauth link
      tags:
      - auth
    post:
      consumes:
      - application/json
      description: 각 provider에 의한 Oauth callback 로직
      parameters:
      - description: Authentication provider
        in: path
        name: provider
        required: true
        type: string
      - description: Oauth code
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/dto.OauthRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved auth URL
          schema:
            $ref: '#/definitions/dto.OauthResponse'
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      summary: oauth
      tags:
      - auth
  /users:
    patch:
      consumes:
      - application/json
      description: 유저 정보 수정
      parameters:
      - description: name
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated
          schema:
            $ref: '#/definitions/dto.UpdateUserResponse'
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      summary: User Update
      tags:
      - users
swagger: "2.0"
